### ISSUE TITLE
False positive for CustomEvent constructor on IE11

### ISSUE THREAD

**Issue by ronen-e** [jokeyrhyme/is-dom4-supported#2]
IE has CustomEvent but cannot be used as a constructor
This code throws an exception on IE11 even though it passes your test.
```javascript
var event = new CustomEvent('customevent');
```

I haven't checked on IE10 but it may also output a false positive.

You should check using CustomEvent as a constructor in addition or instead of the normal test to make sure it works on IE like this:
```javascript
function isCustomEventSupported() {
    var result = false;
    try {
        var e = new CustomEvent('test');
        result = true;
    } catch (e) {}

    return result;
}
```

**Comment by jokeyrhyme** [comment]
@ronen-e good find!

The original intent for this project was to help identity environment that would support Polymer with/without the WebComponents poly-fills. That poly-fill includes a fix for IE's `CustomEvent`:
- https://github.com/webcomponents/webcomponentsjs/blob/v0.7.12/CustomElements.js#L950

There's also a standalone project that provides such a fix all by itself:
- https://github.com/webmodules/custom-event

I guess I'm a bit torn. If I improve the accuracy of the `CustomEvent` test here, then the result will be `false`, even in environments that are otherwise suitable for Polymer.

But if I don't improve the accuracy of the test here, then the result is not useful for other purposes.

I even considered incorporating one of the `CustomEvent` polyfills in this project itself, although I think side-effects like that would be out of scope for this project.

Any ideas?

**Comment by ronen-e** [comment]
I suppose that's really up to you but I myself would pick the most accurate test.

Also, if the original intent of the project was to decide whether or not to use the WebComponents polyfill and I see that same polyfill does indeed perform a check for CustomEvent as a function (`in IE it's a plain non-callable object`) I would definitely follow along and change your code to match theirs.

I might allow for optional settings like:
```javascript
var options = { PolymerWebComponentsPolyfillTestsOnly: true };
var isDOM4Supported = require('is-dom4-supported')(options);
```

**Comment by jokeyrhyme** [comment]
Options seems like a good way to resolve this.

There could even be an option to return a detailed Object similar to Modernizr.

For example:
```js
return {
  customEvents: false,
  domLevel1: true,
  domLevel2: true,
  domLevel3: true,
  eventTargets: true,
  fullSupport: false
};
```

**Comment by jokeyrhyme** [comment]
This should be fixed in v2. Let me know if you notice any other problems. Thanks!
